http:
  port: 8081

registerer:
  register_url: "http://localhost:8080/api/hash/register-worker"
  self_port: 8081

notifier:
  notify_url: "http://localhost:8080/api/tasks/ready"

workers:
  max_parallel: 10